### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by TomerGamerTV** [ImNotSatan/RepoManagerDeluxe#1]
Then opening it just shows blank cmd window and then closing

**Comment by ImNotSatan** [comment]
Any error message?
Did you try running as admin?
What OS are you trying?
32 or 64bit?

Can you try v0.0.2 by the way?

**Comment by TomerGamerTV** [comment]
> Any error message?
> 
> Did you try running as admin?
> 
> What OS are you trying?
> 
> 32 or 64bit?
> 
> 
> 
> Can you try v0.0.2 by the way?

Yes I will try but it’s just showing blank cmd screen and closing

**Comment by TomerGamerTV** [comment]
oh I didn't see what I need to put the exe it the folder (I was thinking about it)
thx for helping 

I think you need to make a wiki page
