### ISSUE TITLE
[0.0.3] Created repos cant add Cydia

### ISSUE THREAD

**Issue by symbuzzer** [ImNotSatan/RepoManagerDeluxe#2]
avalibeyaz.com/repo

you can reach repo files from this link. (no index.htm used for this)

created by 0.0.2

**Comment by ImNotSatan** [comment]
I added your repo just fine,
By the way the newest release is still called 0.0.2 but is actually 0.0.3
Can you try the newest version?

**Comment by symbuzzer** [comment]
which installer u use, cydia?
I tried 0.0.2, I cant see 0.0.3 anywhere

**Comment by ImNotSatan** [comment]
(I just uploaded v0.0.3)
It is working with zebra, the problem is
Your server loads:
avalibeyaz.com/repo/Packages
As text,
And for example my github repo.
http://imnotsatan.github.io/Packages
Downloads the file when opened.

Ill try to add BZIP support in the next version (0.0.4) so it can create Packages.bz2 aswell.

**Comment by symbuzzer** [comment]
still cant work on cydia wth this url: avalibeyaz.com/repo/Packages :(
I cant add my repo

**Comment by ImNotSatan** [comment]
I added a bz2 extention in 0.0.5 could you try that?
(That will create Packages.bz2 aswell)

**Comment by symbuzzer** [comment]
no, it still cant be add to cydia on v0.0.5. I extracted bz2extention_unpack_this_in_repo_folder.rar
to repo folder and re-save but no luck :(

**Comment by ImNotSatan** [comment]
It looks like your repo is working fine right now, but it doesnt have any debs in it.
Try adding 1 deb and it should work

Since i see:
http://avalibeyaz.com/repo/debs/
Is empty

**Comment by symbuzzer** [comment]
ok it works, thanks.

**Comment by ImNotSatan** [comment]
Good to hear its working now, let me know if there are any other bugs :)!
